[package]
name = "swamp-script-analyzer"
version = "0.0.7"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "analyzer for swamp script"

[dependencies]
tracing = "0.1.40"
seq-map = "0.0.13"

swamp-script-semantic = { path = "../semantic", version = "0.0.7" }
swamp-script-ast = { path = "../ast", version = "0.0.7" }
