[package]
name = "swamp-script-error-report"
version = "0.0.7"
edition = "2021"

[dependencies]
swamp-script-semantic = { path = "../semantic", version = "0.0.7" }
swamp-script-source-map = { path = "../source-map", version = "0.0.7" }
swamp-script-analyzer = { path = "../analyzer", version = "0.0.7" }
eira = { path = "../eira", version = "0.0.1" }
