[package]
name = "swamp-script-eval-loader"
version = "0.0.15"
edition = "2024"
license = "MIT"
description = "load swamp-scripts"
repository = "https://github.com/swamp/script"

[dependencies]
swamp-script-ast = { path = "../ast", version = "0.0.15" }
swamp-script-dep-loader = { path = "../dep-loader", version = "0.0.15" }
swamp-script-analyzer = { path = "../analyzer", version = "0.0.15" }
swamp-script-semantic = { path = "../semantic", version = "0.0.15" }
swamp-script-source-map = { path = "../source-map", version = "0.0.15" }
tracing = "0.1.41"
regex = "1.11.1"

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }
swamp-script-parser = { path = "../parser", version = "0.0.15" }
