[package]
name = "swamp-script-eval-loader"
version = "0.0.2-a03"
edition = "2021"
license = "MIT"
description = "load swamp-scripts"

[dependencies]
swamp-script-ast = { path = "../ast", version = "0.0.2-a03" }
swamp-script-dep-loader = { path = "../dep-loader", version = "0.0.2-a03" }
swamp-script-analyzer = { path = "../analyzer", version = "0.0.2-a03" }
swamp-script-semantic = { path = "../semantic", version = "0.0.2-a03" }
