[package]
name = "swamp-script-semantic"
version = "0.0.2-a03"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "semantic types for swamp script"

[dependencies]
swamp-script-ast = { path = "../ast", version = "0.0.2-a03" }
seq-map = "0.0.11"
tracing = "0.1.40"
fixed32 = "0.0.17"
seq-fmt = "0.0.1"

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }
