[workspace]
resolver = "2"
members = [
    # Root orchestrator
    "crates/swamp",
    # Compile orchestrator
    "crates/compile",
    # Parser, AST
    "crates/ast",
    "crates/parser",
    # Analyzer, Semantic, ASG
    "crates/semantic",
    "crates/types",
    "crates/analyzer",
    # Dependency
    "crates/modules",
    "crates/dep-loader",
    "crates/program-analyzer",
    # Core and Std
    "crates/core",
    "crates/core-extra",
    "crates/std",
    "crates/err",
    # Debug
    "crates/pretty-print",
    # Code generator
    "crates/code-gen",
    "crates/code-gen-program",
    # VM, move to own repo in the far future
    "crates/vm",
    "crates/vm-test",
    "crates/vm-disasm",
    "crates/vm-types",
    "crates/vm-instr-build",
    "crates/vm-host",
    # Evaluator, hopefully soon deprecated
    "crates/eval",
]
