[package]
name = "swamp"
version = "0.1.11"
edition = "2024"
license = "MIT"
repository = "https://github.com/swamp/swamp"
description = "script language for embedding"

[dependencies]
# Parser
swamp-parser = { path = "../parser", version = "0.1.11" } # TODO: This is only for an error. parser should not be a dependency

# Semantic and Analyzer
swamp-dep-loader = { path = "../dep-loader", version = "0.1.11" }
swamp-program-analyzer = { path = "../program-analyzer", version = "0.1.11" }
swamp-semantic = { path = "../semantic", version = "0.1.11" }
swamp-types = { path = "../types", version = "0.1.11" }
swamp-analyzer = { path = "../analyzer", version = "0.1.11" }
swamp-modules = { path = "../modules", version = "0.1.11" }

# Core
swamp-core = { path = "../core", version = "0.1.11" }
swamp-core-extra = { path = "../core-extra", version = "0.1.11" }

# Compile orchestrator
swamp-compile = { path = "../compile", version = "0.1.11" }

swamp-error-report = { path = "../err", version = "0.1.11" }

# Runner
swamp-eval = { path = "../eval", version = "0.1.11" }

# Upcoming Runtime
swamp-code-gen-program = { path = "../code-gen-program", version = "0.1.11" }

# Source Map
source-map-cache = "0.0.1"
source-map-node = "0.0.1"

tiny-ver = "0.1.2"

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }
tracing = "0.1.40"
