[package]
name = "swamp-script-ast"
version = "0.0.5"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "ast types for swamp script"

[dependencies]
seq-map = "0.0.12"
fixed32 = "0.0.17"
