[package]
name = "swamp-script-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
pest = "2.7.14" # TODO: remove pest
tracing = "0.1.40"


tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = [
    "registry",
    "env-filter",
] }




# Ast and Parser
swamp-script-parser = { path = "../parser", version = "0.0.1" }
swamp-script-ast = { path = "../ast", version = "0.0.1" }

# Semantic and Analyzer
swamp-script-semantic = { path = "../semantic", version = "0.0.1" }
swamp-script-analyzer = { path = "../analyzer", version = "0.0.1" }

# Runner
swamp-script-eval = { path = "../eval", version = "0.0.1" }



[[bin]]
name = "swamp"
path = "src/main.rs"
