[package]
name = "swamp-script-derive"
version = "0.0.2-a03"
edition = "2021"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full", "extra-traits"] }


[lib]
proc-macro = true
