[package]
name = "swamp-vm-instr-build"
version = "0.1.9"
edition = "2024"
license = "MIT"
description = "builds opcodes for the swamp vm"
repository = "https://github.com/swamp/script"


[dependencies]
swamp-vm-types = { path = "../vm-types", version = "0.1.9" }
