[package]
name = "swamp-script-parser"
version = "0.0.5"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "parser for swamp script"


[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
seq-map = "0.0.11"
tracing = "0.1.40"
fixed32 = "0.0.17"

swamp-script-ast = { path = "../ast", version = "0.0.5" }

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }
