# The URL the site will be built for
base_url = "https://swamp-lang.org"
title = "Swamp Language"
theme = "deepthought"
compile_sass = true
build_search_index = true


[markdown]
highlight_code = true
highlight_theme = "ayu-dark" # "one-dark" "base16-ocean-dark"
# extra_syntaxes = ["syntax-themes"]  # Not sure if this is needed?
extra_syntaxes_and_themes = ["syntax-themes"]


[extra]
author = "Swamp Team"
description = "Official documentation for the Swamp programming language"
show_social = true

# Navigation - DeepThought
navbar_items = [
  { code = "en", nav_items = [
    { url = "/", name = "Home" },
    { url = "/specification/", name = "Specification" },
    { url = "/roadmap/", name = "Roadmap" },
  ]}
]

# Footer items - DeepThought
footer_items = [
  { code = "en", nav_items = [
    { url = "/", name = "Home" }
    # { url = "/docs/", name = "Docs" },
    # { url = "/blog/", name = "Blog" },
  ]}
]

is_dark = true 


[extra.footer]
info = 'Copyright 2024 Peter Bjorklund. All rights reserved. https://github.com/swamp/script'

[extra.social]
github = "swamp/script"
