[package]
name = "swamp-vm-host"
version = "0.1.8"
edition = "2024"
license = "MIT"
description = "host interface for the swamp VM"
repository = "https://github.com/swamp/script"

[dependencies]
swamp-vm = {path= "../vm", version = "0.1.8" }
