[package]
name = "swamp-vm-host"
version = "0.1.6"
edition = "2024"
license = "MIT"
description = "host interface for the swamp VM"
repository = "https://github.com/swamp/script"

[dependencies]
swamp-vm = {path= "../vm", version = "0.1.6" }
