[package]
name = "swamp-vm-host"
version = "0.0.14"
edition = "2024"
license = "MIT"
description = "host interface for the swamp VM"
repository = "https://github.com/swamp/swamp"

[dependencies]
swamp-vm = {path= "../vm", version = "0.0.14" }
