[package]
name = "swamp-script-node"
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "compiler node with documentation and meta information"

[dependencies]
