[package]
name = "swamp-node"
version = "0.1.10"
edition = "2024"
license = "MIT"
repository = "https://github.com/swamp/swamp"
description = "compiler node with documentation and meta information"

[dependencies]
