[package]
name = "swamp-script-source-map"
version = "0.0.8"
edition = "2021"

[dependencies]
seq-map = "0.0.13"
tracing = "0.1.41"
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }
pathdiff = "0.2.3"
