[package]
name = "swamp-vm-test"
version = "0.1.10"
edition = "2024"
license = "MIT"
description = "examples and tests on how to use the swamp vm with swamp"
repository = "https://github.com/swamp/swamp"

[dependencies]
swamp-vm = { path = "../vm", version = "0.1.10", features = [] }
swamp-vm-types = { path = "../vm-types", version = "0.1.10", features = [] }
swamp-code-gen = { path = "../code-gen", version = "0.1.10" }
swamp-compile = { path = "../compile", version = "0.1.10" }
hexify = "0.0.3"
swamp-types = { path = "../types", version = "0.1.10" }
swamp-semantic = { path = "../semantic", version = "0.1.10" }
swamp-vm-disasm = { path = "../vm-disasm", version = "0.1.10" }
swamp-code-gen-program = { path = "../code-gen-program", version = "0.1.10" }
source-map-cache = "0.0.1"

tracing = "0.1.40"
seq-map = "0.0.13"

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }

[[bench]]
name = "benchmark"
harness = false
