[package]
name = "eira"
version = "0.0.12"
edition = "2021"
license = "MIT"
description = "Ansi-colored error reporting output"
repository = "https://github.com/piot/eira"

[dependencies]
yansi = "1.0.1"
