[package]
name = "eira"
version = "0.1.9"
edition = "2024"
license = "MIT"
description = "Ansi-colored error reporting output"
repository = "https://github.com/piot/eira"

[dependencies]
yansi = "1.0.1"
