[package]
name = "swamp-script-derive-tests"
version = "0.0.11"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "tests for swamp macro"

[dependencies]
swamp-script-derive = { path = "../derive" , version = "0.0.11" }

[dev-dependencies]
swamp-script-derive = { path = "../derive" , version = "0.0.11" }
swamp-script-semantic = { path = "../semantic" , version = "0.0.11" }
swamp-script-core = { path = "../core" , version = "0.0.11" }
