[package]
name = "swamp-script"
version = "0.0.2-a03"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "script language for embedding"

[dependencies]

# Ast and Parser
swamp-script-parser = { path = "../parser", version = "0.0.2-a03" }
swamp-script-ast = { path = "../ast", version = "0.0.2-a03" }

# Semantic and Analyzer
swamp-script-semantic = { path = "../semantic", version = "0.0.2-a03" }
swamp-script-analyzer = { path = "../analyzer", version = "0.0.2-a03" }

# Runner
swamp-script-eval = { path = "../eval", version = "0.0.2-a03" }

swamp-script-dep-loader = { path = "../dep-loader", version = "0.0.2-a03" }
