[package]
name = "swamp-script"
version = "0.0.14"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "script language for embedding"

[dependencies]

swamp-script-source-map = { path = "../source-map", version = "0.0.14" }

# Ast and Parser
swamp-script-parser = { path = "../parser", version = "0.0.14" }
swamp-script-ast = { path = "../ast", version = "0.0.14" }

# Semantic and Analyzer
swamp-script-semantic = { path = "../semantic", version = "0.0.14" }
swamp-script-analyzer = { path = "../analyzer", version = "0.0.14" }

swamp-script-error-report = { path = "../err", version = "0.0.14" }

# Core and Std
swamp-script-core-extra = { path = "../core-extra", version = "0.0.14" }
swamp-script-std = { path = "../std", version = "0.0.14" }

# Runner
swamp-script-eval = { path = "../eval", version = "0.0.14" }
swamp-script-dep-loader = { path = "../dep-loader", version = "0.0.14" }
swamp-script-eval-loader = { path = "../eval-loader", version = "0.0.14" }
swamp-script-source-map-lookup = { path = "../source-map-lookup", version = "0.0.14" }
