[package]
name = "swamp-vm-types"
version = "0.0.14"
edition = "2024"
license = "MIT"
description = "Low-level types for memory layout, addresses, and instructions used by the Swamp Virtual Machine (VM)."
repository = "https://github.com/swamp/swamp"

[dependencies]
