[package]
name = "swamp-script-std"
version = "0.0.14"
edition = "2021"
license = "MIT"
repository = "https://github.com/swamp/script"
description = "standard library for swamp"

[dependencies]
swamp-script-semantic = { path = "../semantic", version = "0.0.14" }
