[package]
name = "swamp-script-eval"
version = "0.0.1"
edition = "2021"

[dependencies]
swamp-script-ast = { path = "../ast", version = "0.0.1" }
swamp-script-parser = { path = "../parser", version = "0.0.1" }
swamp-script-derive = { path = "../derive", version = "0.0.1" }
seq-map = "0.0.8"
tracing = "0.1.40"

[dev-dependencies]
test-log = { version = "0.2.16", features = ["trace", "log", "color"] }
