[package]
name = "swamp-script-code-gen"
version = "0.1.4"
edition = "2024"
license = "MIT"
description = "generates swamp-vm opcodes"
repository = "https://github.com/swamp/script"

[dependencies]
# Swamp VM
swamp-vm-types = { path = "../vm-types", version = "0.1.4" }
swamp-vm-instr-build = { path = "../vm-instr-build", version = "0.1.4" }

# Swamp script
swamp-script-semantic = { path = "../semantic", version = "0.1.4" }
swamp-script-types = { path = "../types", version = "0.1.4" }

seq-map = "0.0.13"
tracing = "0.1.40"
