[package]
name = "time-dilation"
version = "0.1.8"
edition = "2024"
license = "MIT"
description = "checks the time passed"
repository = "github.com/swamp/script"

[dependencies]
[features]
default = []
# This feature controls whether the summary is printed on drop
enable_summary = []
