name: Build

on:
  push:
    branches:
      - "*" # All branches for now

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
            arch: x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install librust-alsa-sys-dev libudev-dev

      - name: Install Rust 1.85.0
        run: rustup update stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - run: RUSTFLAGS="-D warnings" cargo clippy --color=always # -- -Wclippy::pedantic

      - name: Build
        run: cargo build --color=always --all-features --target ${{ matrix.target }}
