name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux
            arch: x86_64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows
            arch: x86_64

          - os: macos-latest
            target: x86_64-apple-darwin
            platform: darwin
            arch: x86_64

          - os: macos-latest
            target: aarch64-apple-darwin
            platform: darwin
            arch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install librust-alsa-sys-dev libudev-dev

      - name: Install Rust 1.85.0
        run: rustup update stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Install zip (Windows) # Zip is not installed in the runner, love it :)
        if: matrix.os == 'windows-latest'
        run: choco install zip

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
